#Лабораторная работа №3: Кластерный анализ методом DBSCAN

In [9]:
#  Активируем библиотеки

import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
%matplotlib inline

from sklearn import preprocessing

import os

In [10]:
#  Активируем процедуру DBSCAN

from sklearn.cluster import DBSCAN

In [11]:
data = './Econom_Cities_data.csv'
df = pd.read_csv(data, sep=';', decimal=',',  index_col='City')
df.head(10)

Work  Price  Salary
City                             
Amsterdam     1714   65.6    49.0
Athens        1792   53.8    30.4
Bogota        2152   37.9    11.5
Bombay        2052   30.3     5.3
Brussels      1708   73.8    50.5
Buenos_Aires  1971   56.1    12.5
Cairo        -9999   37.1 -9999.0
Caracas       2041   61.0    10.9
Chicago       1924   73.9    61.9
Copenhagen    1717   91.3    62.9

In [91]:
#Имея информацию из предыдущей лабы удалим выбросы
clean_df = df.drop(['Jakarta', 'Cairo'])

In [92]:
#Стандартизируем так как данные в разных диапазонах
std = preprocessing.StandardScaler()
std.fit(clean_df)
std_df = std.transform(clean_df)
std_df = pd.DataFrame(std_df, index = clean_df.index, columns = clean_df.columns)
std_df.head(10)

Work     Price    Salary
City                                      
Amsterdam    -0.962166 -0.212712  0.386095
Athens       -0.509827 -0.770489 -0.373488
Bogota        1.577891 -1.522069 -1.145323
Bombay        0.997969 -1.881316 -1.398517
Brussels     -0.996961  0.174896  0.447351
Buenos_Aires  0.528233 -0.661769 -1.104485
Caracas       0.934178 -0.430150 -1.169825
Chicago       0.255670  0.179623  0.912902
Copenhagen   -0.944768  1.002108  0.953740
Dublin       -0.701201  0.278888  0.075727

In [93]:
# Создаем объект DBSCAN
dbscan_1 = DBSCAN(eps=0.5, metric='euclidean', min_samples=5)

# Обучим модель
dbscan_1.fit(std_df)

dbscan_1.labels_

array([ 0, -1, -1, -1,  0, -1, -1, -1, -1,  0,  0, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  0, -1, -1, -1, -1, -1,  0,  0, -1, -1, -1, -1, -1,  0,
       -1, -1, -1, -1, -1,  0, -1, -1, -1, -1,  0, -1])

In [94]:
unique, counts = np.unique(dbscan_1.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[-1 36]
 [ 0 10]]


Слишком много выбросов, попробуем повысить eps = 2.

In [95]:
dbscan_2 = DBSCAN(eps=2, metric='euclidean', min_samples=5)

dbscan_2.fit(std_df)

dbscan_2.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [96]:
unique, counts = np.unique(dbscan_2.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[ 0 46]]


Избавились от выбросов совсем и не видим разбиение на класеры попробуем понизить eps = 1.5, также уменьшим min_samples = 4

In [97]:
dbscan_3 = DBSCAN(eps=1.5, metric='euclidean', min_samples=4)

dbscan_3.fit(std_df)

dbscan_3.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [98]:
unique, counts = np.unique(dbscan_3.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[-1  1]
 [ 0 45]]


Появился 1 выброс и остался один большой кластер, поэтому продолжаем понижать

In [99]:
dbscan_4 = DBSCAN(eps=0.8, metric='euclidean', min_samples=3)

dbscan_4.fit(std_df)

dbscan_4.labels_

array([ 0,  1,  1,  1,  0,  1,  1,  0,  0,  0,  0,  0, -1, -1, -1,  0,  1,
        1,  1,  1,  0,  0,  0,  0,  1,  1,  0,  0,  1,  0,  1, -1,  1,  0,
        1,  1,  1,  1, -1,  0, -1,  1, -1,  0,  0, -1])

In [100]:
unique, counts = np.unique(dbscan_4.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[-1  8]
 [ 0 19]
 [ 1 19]]


In [101]:
dbscan_5 = DBSCAN(eps=0.8, metric='euclidean', min_samples=2)

dbscan_5.fit(std_df)

dbscan_5.labels_

array([ 0,  1,  1,  1,  0,  1,  1,  0,  0,  0,  0,  0,  2,  3, -1,  0,  1,
        1,  1,  1,  0,  0,  0,  0,  1,  1,  0,  0,  1,  0,  1,  3,  1,  0,
        1,  1,  1,  1, -1,  0, -1,  1, -1,  0,  0,  2])

In [102]:
unique, counts = np.unique(dbscan_5.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[-1  4]
 [ 0 19]
 [ 1 19]
 [ 2  2]
 [ 3  2]]


Получившийся вариант выглядит наиболее правдивым, поэтому для анализа выберем его

In [104]:
clean_df['dbscan_5'] = dbscan_5.labels_
clean_df.groupby('dbscan_5').mean()

Work       Price     Salary
dbscan_5                                    
-1        2051.250000   93.600000  42.375000
 0        1792.000000   77.526316  55.157895
 1        1959.210526   50.115789  14.789474
 2        1874.000000   97.950000  95.150000
 3        1625.000000  114.550000  65.150000

Кластер -1(выброс) - люди в этих городах много работают, мало зарабатывают, относительно зарплат имеют высокие цены на "жизнь";
Кластер 0 - хороший баланс зарплат, рабочего времени и цен, относительно других городов, в этих городах в среднем получают больше, чем в остальных;
Кластер 1 - города, в которых люди много работают, мало получают, а также очень высокие цены на жизнь;
Кластер 2 - предположительно самые благоприятные города, где люди работают немного относительно других, получают одни из самых высоких зарплат(в анализируемых городах), цены на жизнь хоть и высокие, но по отношению к ЗП нормальные.
Кластер 3 - в этих городах люди работают меньше всех(анализируемых), получают среднюю зарплату, но при этом самые высокие цены на жизнь.